<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SnapDroid.Core\SnapDroid.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>snapdroid</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>SnapDroid.Cli</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
