<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClipLink.Core\ClipLink.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>cliplink</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>ClipLink.Cli</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
